#ifndef _EXCEPTIONS_H_
#define _EXCEPTIONS_H_

#include <define.h>

#define _EXCEPTION_DECLARE(NUMBER) void exception_ ## NUMBER ()

_EXCEPTION_DECLARE(00);
_EXCEPTION_DECLARE(02);
_EXCEPTION_DECLARE(03);
_EXCEPTION_DECLARE(04);
_EXCEPTION_DECLARE(05);
_EXCEPTION_DECLARE(06);
_EXCEPTION_DECLARE(07);
_EXCEPTION_DECLARE(08);
_EXCEPTION_DECLARE(09);
_EXCEPTION_DECLARE(0A);
_EXCEPTION_DECLARE(0B);
_EXCEPTION_DECLARE(0C);
_EXCEPTION_DECLARE(0D);
_EXCEPTION_DECLARE(0E);
_EXCEPTION_DECLARE(10);
_EXCEPTION_DECLARE(11);
_EXCEPTION_DECLARE(12);
_EXCEPTION_DECLARE(13);

#endif