#ifndef _SYSCALLS_H_
#define _SYSCALLS_H_

enum syscall_triggers { 
	_SYSCALL_READ = 0,
	_SYSCALL_WRITE,
	_SYSCALL_TIME,
	_SYSCALL_TERMINAL_SELECT,
	_SYSCALL_TERMINAL_CLEAR,
	_SYSCALL_TERMINAL_COLOR,
	_SYSCALL_TERMINAL_CURSOR
	// (1) FUTURE SYSCALL HERE !! REMEMBER TO CHANGE _SYSCALLS_LAST !!
};

#define _SYSCALLS_LAST _SYSCALL_TERMINAL_CURSOR
#define _SYSCALLS_SIZE (_SYSCALLS_LAST + 1)

#endif