#ifndef _SYSCONSOLE_H_
#define _SYSCONSOLE_H_

#include <sysvideo.h>

#define _OUTPUT_ERROR_TERMINAL_INVALID -1
#define _OUTPUT_ERROR_SLEEP_ACTIVE -2
#define _OUTPUT_ERROR_SLEEP_NOT_ACTIVE -3
#define _OUTPUT_ERROR_SLEEP_TIME -4
#define _SYSCALL_ERROR_SCREEN_OPERATION_INVALID -5

#define _OUTPUT_TERMINAL_SIZE 2
#define _OUTPUT_TERMINAL_MIN 0
#define _OUTPUT_TERMINAL_MAX (_OUTPUT_TERMINAL_SIZE - 1)

#define _OUTPUT_TERMINAL_DEFAULT 0

#define _OUTPUT_SLEEP_TIME_MIN 5

enum terminal_color_ops {
	_TERMINAL_COLOR_OPERATION_TEXT = 0,
	_TERMINAL_COLOR_OPERATION_BG,
	_TERMINAL_COLOR_OPERATION_STYLE,
};

#endif
